### ISSUE TITLE
[ENH] MG performance regression tests and tracking

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1085]
Could be done as part of #1203 

We need to track MG :
- [ ] performance regression / improvements
- [ ] memory usage (for scalability tracking)

From #1003 :
- [ ] Twitter, and hibench bigdata(x2,x4...)
- [ ] 2, 4, and more GPUs if available
- [ ] Every step starting from reading
- [ ] Record results in a drive spreadsheet
- [ ] Fill issues if performance problems need to be addressed

This is for performance analysis and different than the multi-node testing issue.

**Comment by BradReesWork** [comment]
closed - being tracked on other issues
