### ISSUE TITLE
[ENH] Gunrock Integration EPIC

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#1263]
This epic is intended to describe the major activities required for integrating Gunrock components.  The intention is to link this EPIC to issues in both the cugraph and gunrock so that we can track all of the work in one place.

There are a couple of major areas we want to address in this epic.

1. Building/incorporating gunrock.  Making changes to how gunrock is built and how it is integrated into cugraph.
1. Using a C++ API instead of a C API for accessing functions

The following issues in the gunrock repository are relevant to cugraph to gunrock integration:
 - [ ] https://github.com/gunrock/gunrock/issues/816
 - [ ] https://github.com/gunrock/gunrock/issues/817
 - [ ] https://github.com/gunrock/gunrock/issues/818
 - [ ] https://github.com/gunrock/gunrock/issues/819
 - [ ] https://github.com/gunrock/gunrock/issues/820
 - [ ] https://github.com/gunrock/gunrock/issues/821 ** Note that MaxFlow is not ready for integration
 - [ ] https://github.com/gunrock/gunrock/issues/822
 - [ ] https://github.com/gunrock/gunrock/issues/823 ** Note that GraphSage is currently inference onlyl
 - [ ] https://github.com/gunrock/gunrock/issues/824
 - [ ] https://github.com/gunrock/gunrock/issues/825
 - [ ] https://github.com/gunrock/gunrock/issues/826
 - [ ] https://github.com/gunrock/gunrock/issues/814

In our meeting with gunrock, we identified this as the final impediment to their moving away from moderngpu:
 - https://github.com/NVIDIA/thrust/issues/331 - it is unclear if anyone is working on this issue.

- [ ] #705  Subgraph Matching
- [ ] #1234 A*
- [ ] MaxFlow  ** Note, the MaxFlow algorithm in gunrock is not ready for integration
- [ ] GraphColoring

Dropping
* RMAT from Gunrock
* RandomWalk from Gunrock
