### ISSUE TITLE
Algorithm Migration - ECG

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1284]
Implement ECG for Multi-Node Multi-GPU
```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/cugraph/issues/3569
- [ ] https://github.com/rapidsai/cugraph/issues/3570
- [ ] https://github.com/rapidsai/cugraph/issues/3571
- [ ] https://github.com/rapidsai/cugraph/issues/3572
- [ ] https://github.com/rapidsai/cugraph/issues/3573
- [ ] https://github.com/rapidsai/cugraph/issues/3574
- [ ] https://github.com/rapidsai/cugraph/issues/3575
- [ ] https://github.com/rapidsai/cugraph/issues/3576
- [ ] https://github.com/rapidsai/cugraph/issues/3577
- [ ] https://github.com/rapidsai/cugraph/issues/3578
- [ ] https://github.com/rapidsai/cugraph/issues/3579
- [ ] https://github.com/rapidsai/cugraph/issues/3580
- [ ] #2494 
- [ ] https://github.com/rapidsai/cugraph/issues/3764
```
