### ISSUE TITLE
[EPIC] Support benchmarks at scale

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1382]
The goal is to get cuGraph running benchmarks on 128 or more GPUs.

- [x] Integrate R-mat generator
- [x] Input / output validation (may also need to be distributed due to scale)
- [x] identify all required components and add here
