### ISSUE TITLE
[EPIC] Refactor Notebooks

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1405]
Refactor the notebooks to be more topic focus and less one notebook per function.   The goal is to provide insight into what and why about the algorithms as well as simple API example

- [x] Refactor Centrality
- [x] Refactor Community
   - [ ] move out TC and Subgraph Extraction
- [x] Refactor Componenets
- [x] Refactor Core
- [x] Refactor Link Analysis
- [x] Refactor Link Prediction
- [ ] Refactor Traversal
- [ ] Refactor Sampling
- [ ] Refactor Structure

Related Issues:
 We have a lot of redundant code which is mostly obvious to users and doesn't add overall value to the notebook UX by having repeated inline in each notebook. We obviously still need the functionality, but we could improve the UX by adding a simple set of utilities - or reusing existing utilities from elsewhttps://github.com/rapidsai/cugraph/pull/1927#discussion_r743824898 - and updating the notebooks to call them.

An example of where this comes up is here.
