### ISSUE TITLE
[FEA] Refactor cugraph Python layer

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#141]
**Is your feature request related to a problem? Please describe.**
The current python bindings implementation encapsulates everything in the cython and C code.  This makes a number of things awkward, since C structures/objects cannot be passed to python code.

**Describe the solution you'd like**
I believe that we should create a richer python side of the interface.  Both cudf and cuml have a much richer python side of the interface, and the result is much more flexibility and a much easier interface to work with.

**Describe alternatives you've considered**
N/A

**Task List**

- [ ] Design new code structure for python bindings

- [ ] Move graph structure into python

- [ ] Reimplement all methods

**Additional context**
