### ISSUE TITLE
[FEA] Improve cugraph Python package structure from monolithic Cython extension

### ISSUE THREAD

**Issue by dantegd** [rapidsai/cugraph#146]
**Is your feature request related to a problem? Please describe.**
Following the recent issues of Python refactor, this feature request follows that spirit of highly improving cuGraph's Cython/Python layer.
 
The current structure of cugraph is simlar to the old cuML, where there is one central cython file `cugraph.pyx` which includes all the other cython sources, and ends up creating a cython extension `cugraph` but it is not a proper python package. 

This has quite a few disadvantages (for example, custom pytest fixtures will probably not work, cannot have selective compilation of only certain modules and other thigns) and is not the standard way of doing this. And its the source of having to delete a .cpp file to force Cython to recompile, since changes in the files included in `cugraph.pyx` are not detected by Cython so it doesn't recythonize/recompile. With a proper python package structure, cython automatically would only cythonize the changed files. 

The setup.py changes also make it that new `.pyx` can be found automatically and instead of needing manual entries in `cugraph.pyx`. 

Additionally, not every function binding to C++ requires a `.pxd` header file, so functions that are not going to have reuse beyond a single `pyx` might be better off included in the `pyx` to reduce complexity of the repository with less files. 

**Describe the solution you'd like**
Proper package cython structure, see relevant PR for cuML: https://github.com/rapidsai/cuml/pull/236

**Describe alternatives you've considered**
Other alternatives would be hard to justify, since cuDF and cuML follow the approach  described, and it's the standard way of creating a Python package (with or without Cython extensions in it). 

**Task List**

- [ ] Remove cugraph.pyx
- [ ] Update `setup.py` and `setup_pip.py`
- [ ] Add Python `__init__.py` files in the folders to make them modules
- [ ] Ensure consistency in naming and importing is preserved after changes.
- [ ] Test that everything works as expected, including automatic detection of files changed by Cythonization process.
