### ISSUE TITLE
[EPIC] SG Multi-Source BFS (with aggregated frontier)

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1465]
The primary goal is to support BFS workflows with few sources per component/graphs which typically come with large datasets. Highly heterogeneous graph/component sizes are expected. A naive round-robin BFS execution for each source would lead to pathological under-occupancy. This is particularly problematic if the component sizes have a long tail distribution. In addition, a naive loop over BFS would explode the memory requirements and inefficiently encode sparse data into a dense output format. 
A solution based on more advanced traversal primitives with dynamic frontier allocation and sparse output is needed to address this problem.
 
Another related workflow has many sources in one graph with one or a few components. This requires controlling the number of seeds that get processed simultaneously in-memory and potentially offloading output. Notice that a single GPU-sized graph with one component can generate PetaBytes of output depending on the number of seeds. 

This project will lay the foundation for the multi-GPU versions, as well as for SSSP applications to APSP. The two workflows described above result in different multi-GPU/multi-node paths where the former faces a distributed graph challenge and the latter would be addressed with batch techniques.

Supported inputs
1) List of graphs (edge lists) with a list of cudf.Series of seeds per edge list
2) Single graph with a cudf.Series of seeds. We allow component offsets information to be passed optionally, when component are not provided memory footprint is in` O(V*n_sources)`

Core part :

- [ ] Aggregated Traversal Graph Prim #1456
- [ ] Artificial multi-component graphs  tests #1458 
- [ ] List of graph to graph conversion #1459 
- [ ] Add feasibility checks for multi seeds APIs #1460 
- [ ] Use aggregated traversal prim in BFS #1457 
- [ ] Bindings for multi source BFS #1462
- [ ] SG multi-seed BFS performance evaluation #1463

Tangential :

- [ ] Extend multi-seed BFS work to SSSP #1464
- [ ] Output offloading in multi source traversals #1461

**Comment by afender** [comment]
Current API proposal for Python :

```Python
def concurrent_bfs(Graphs, sources, depth_limit=None, offload=False):
    """
    Find the breadth first traversals of multiple graphs with multiple sources
    in each graph.

    Parameters
    ----------
    Graphs : list of cugraph.Graph or cugraph.DiGraph
        The adjacency lists will be computed if not already present.

    sources : list of cudf.Series
        For each graph, subset of vertices from which the traversals start. 
        A BFS is run in Graphs[i] for each source in the Series at sources[i].
        The size of this list must match the size of the graph list.
        The size of each Series (ie. the number of sources per graph) is flexible,
        but cannot exceed the size of the corresponding graph.


    depth_limit : Integer, optional, default=None
        Limit the depth of the search. Terminates if no more vertices are
        reachable within the distance of depth_limit

    offload : boolean, optional, default=False
        Indicates if output should be written to the disk. 
        When not provided, the algorithms decides if offloading is needed
        based on the input parameters.

    Returns
    -------
    Return type is decided based on the input parameters (size of
    sources, size of the graph, number of graphs and offload setting)

    If G is a cugraph.Graph and output fits in memory:
        BFS_edge_lists : cudf.DataFrame
            GPU data frame containing all BFS edges
        source_offsets: cudf.Series
            Series containing the starting offset in the returned edge list for each source.

    If offload is True, or if the output does not fit in memory :
        Writes csv files containing BFS output to the disk.
    """
    
    # Consolidate graphs in a single graph and record components

    # Renumber and concatenate sources in a single df 

    # Call multi_source_bfs


def multi_source_bfs(G, sources, components=None, depth_limit=None, offload=False):
    """
    Find the breadth first traversal from multiple sources in a graph.

    Parameters
    ----------
    G : cugraph.Graph or cugraph.DiGraph
        The adjacency list will be computed if not already present.

    sources :  cudf.Series
        Subset of vertices from which the traversals start. A BFS is run for
        each source in the Series. 
        The size of the series should be at least one and cannot exceed the size
        of the graph.

    depth_limit : Integer, optional, default=None
        Limit the depth of the search. Terminates if no more vertices are
        reachable within the distance of depth_limit

    components : cudf.DataFrame, optional, default=None
        GPU Dataframe containing the component information.
        Passing this information may impact the return type.
        When no component information is passed BFS uses one component
        behavior settings.

        components['vertex'] : cudf.Series
            vertex IDs
        components['color'] : cudf.Series
            component IDs/color for vertices.  

    offload : boolean, optional, default=False
        Indicates if output should be written to the disk. 
        When not provided, the algorithms decides if offloading is needed
        based on the input parameters.

    Returns
    -------
    Return value type is decided based on the input parameters (size of
    sources, size of the graph, number of components and offload setting)
    If G is a cugraph.Graph, returns :
       cudf.DataFrame
          df['vertex'] vertex IDs

          df['distance_<source>'] path distance for each vertex from the starting vertex
          One column per source.

          df['predecessor_<source>'] for each i'th position in the column, the vertex ID
          immediately preceding the vertex at position i in the 'vertex' column
          One column per source.

    If G is a cugraph.Graph and component information is present returns :
        BFS_edge_lists : cudf.DataFrame
            GPU data frame containing all BFS edges
        source_offsets: cudf.Series
            Series containing the starting offset in the returned edge list for each source.

    If offload is True, or if the output does not fit in memory :
        Writes csv files containing BFS output to the disk.
    """
    
    # Memory footprint check

    # Call multi_source_bfs

```

**Comment by BradReesWork** [comment]
being dropped since multi-seed BFS needs to run within a single component
