### ISSUE TITLE
[EPIC] 0.20 Release Goals

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1486]
**P0**

- [ ] P0:  Demonstrate MNMG WCC running at Sclae
   -   [ ] Code
         - [ ]  Distributed union-find​ graph primitive
         - [ ]  MNMG WCC​  C/CUDA Code
         - [ ]  WCC Python Bindings​

- [ ] Test 
   - [ ] Test file to run WCC against a RMAT file
   - [ ] 4 GPUs
   - [ ] 8 GPUs
   - [ ] 16 GPUs
   - [ ] 32 GPUs
   - [ ] 64 GPUs
   - [ ] 128 GPUs

- [ ] Routing
   - [ ] Tabu
   - [ ]  Batch TSP

- [ ] Grapg Classes
   - [ ] Graph
   - [ ] Multigraph
   - [ ] Tree

**P1**
- [ ] Batch Framework
   - [ ] Batch Random Walk
   - [ ] Batch TSP

- [ ] Multi-Seed BFS (one seed per component version)

- [ ] Algorithms 
   - [ ] MNMG Leiden
   - [ ] Eigenvector Centrality​
   - [ ] Assortativity Centrality​
   - [ ] Degree Centrality​
   - [ ] Local Cluster Coefficient​
   - [ ] SG SLHC (dependent on cuML pushing code to RAFT)​
