### ISSUE TITLE
[FEA] [SNMG PageRank] Pagerank solver

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#178]
**Is your feature request related to a problem? Please describe.**
We need a C++ PageRank solver feature that assembles the building blocks described in #174 #175 #176 and #177. Then we need C++ API  for it.

**Describe the solution you'd like**
Similar to the SNSG version except that the input edge list is provided as a data frame distributed on multiple GPUs. Since the graph structure is nor multi-GPU yet, the API should accept a regular cuDF data frame for the edge list instead of cuGraph's graph object. 
We should follow modern C++ best practice and use a Pagerank solver class

**Task List**

- [x] C++ solver and API 
- [x] Documentation in `function.h`
- [x] Tests : compare against SNSG version on several large datasets

**Comment by afender** [comment]
closed by #357
