### ISSUE TITLE
[FEA] [SNMG PageRank] Python bindings

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#179]
**Is your feature request related to a problem? Please describe.**
We first need python bindings for the SNMG PageRank solver of issue #178 
Then we can add bindings for coo2csr of issue #174 and degree function of issue #175 

**Describe the solution you'd like**
For Pagerank, it should be similar to the SNSG version except that the input edge list is provided as a data frame distributed on multiple GPUs. Since the graph structure is not multi-GPU yet, the API should accept a regular cuDF data frame for the edge list instead of cuGraph's graph object.

**Task List**
- [x] Python bindings and API (first exposed multi-threaded functions in cuGraph)
- [ ] Pytest testing against NetworkX
- [ ] Documentation
- [ ] Python code example

**Comment by afender** [comment]
Done in #353 #383 #365
