### ISSUE TITLE
[EPIC] Property Graph research and prototype

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#1876]
- [ ] Update design doc
- [ ] Create prototype
  - [ ] Use Nx examples for graph construction with properties
  - [ ] Create prototype PropertyGraph class
  - [ ] Add Nx wrappers to start implementation of Nx compat module
- [ ] Use Nx wrappers and prototype PropertyGraph class to see initial examples work
