### ISSUE TITLE
[EPIC] NetworkX Compat

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#1922]
**22.04**
- [ ] one (or more) e2e workflows for Pagerank and/or BFS identified that currently run to completion with NetworkX. Even better if these are popular examples known by the community.
- [ ] swap out `import networkx as nx` with `from cugraph.experimental import nx` and the workflows still run and produce the same results.
  - [ ] unit tests for the workflow.  These can be either a single unit test for the entire e2e run, or a series of unit tests that cover the entire e2e run in a more fine-grained way.
    - [x] #2035
  - [ ] one or more notebooks started for the e2e runs which can eventually be used as the nx compat demo notebook(s)

**22.06**
- [ ] initial algos (PageRank and BFS)  and performance comparison (use to drive where to optimize)

**22.08**
- [ ] initial release (PageRank, BSF, SSSP, Louvain, WCC, SCC, BC, Jaccard) and performance tuned

**22.10**
- [ ] refactor (cleanup) cuGraph code to remove Nx (this is the "consolidate all Nx compatibility into one place" goal below, meaning that all the code that accepts a NetworkX graph object needs to go into this new nx compatibility module)

<hr>
**Goals**

- Be a drop-in replacement for NetworkX
- `from cugraph.experimental import nx`
- Be faster than native NetworkX
- Consolidate all Nx compatibility into one place

 
Likely areas where we will not be drop-in replacement (but we should discuss this further to gauge the impact and see if there still may be an option to support):
- Likely this: Allow any hashable to be an attribute.  You cannot create “MyData” and then assign it as an attribute

 
Checkboxes / functions

- [ ] add_node
- [ ] add_node_from
- [ ] remove_node
- [ ] remove_node_from
- [ ] nodes
- [ ] number_of_nodes
- [ ] order
- [ ] has_node
- [ ] add_edge
- [ ] add_edge_from
- [ ] add_weighted_edges_from
- [ ] remove_edge
- [ ] removed_edge_from
- [ ] update
- [ ] has_edge
- [ ] neighbors
- [ ] edges
- [ ] get_edge_data
- [ ] adjacency
- [ ] degree
- [ ] clear
- [ ] clear_edges

 
IO

- [ ] read_edgelist
- [ ] read_weighted_edgelist
- [ ] read_adjlist

 
 
 
 
Graph Types

- [ ] Graph
- [ ] DiGraph

 
We need to wait on cuGraph before adding MultiGraph and Bipartite Graph

**Comment by BradReesWork** [comment]
@acostadon can you add some goals to the description?

**Comment by BradReesWork** [comment]
closing issue/epic.   this will be replaced by work with Nx
