### ISSUE TITLE
[EPIC] python/notebook documentation cleanup

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2004]
- [ ] create dataset API
- [ ] update docstrings to use new dataset API
- [ ] update docstrings to work with doctest
- [ ] update `ci/test.sh` to call doctest
- [ ] update notebooks to use new dataset API

**Comment by BradReesWork** [comment]
already in #3368
