### ISSUE TITLE
[GNN] Initial DGL Integration

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2140]
Integrate cuGraph into DGL for Sampling and cugraph-ops functions

- [ ] SG Sampling integrated.  
    - [ ] DGL Graph Storage class (SG Clinet) - in DGL github - #2205
    - [ ] Client class
    - [ ] Code in cuGraph -  #2204

- [ ] MG Sampling integrated into DGL
    - [ ] GaaS client class
    - [ ] DGL code  - #2206
    - [ ] cuGraph code

**Comment by BradReesWork** [comment]
closing and moving to other project boards
