### ISSUE TITLE
[EPIC]  Property Graph - Initial version

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2142]
Create an initial version of Property Graph for use in supporting GNNs supporting a small number of attributes

- [x] Define initial requirements
- [ ] Code initial version #2109 
- [ ] Performance tune
- [ ] Get working with GaaS
- [ ] Update to creating Data Masking
