### ISSUE TITLE
Algorithm Migration - K-Truss

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#2167]
Enhance K-Truss to be MNMG.

### Tasks
- [ ] https://github.com/rapidsai/cugraph/issues/3446
- [ ] https://github.com/rapidsai/cugraph/issues/3447
- [ ] https://github.com/rapidsai/cugraph/issues/3448
- [ ] https://github.com/rapidsai/cugraph/issues/3449
- [ ] https://github.com/rapidsai/cugraph/issues/3450
- [ ] https://github.com/rapidsai/cugraph/issues/3451
- [ ] https://github.com/rapidsai/cugraph/issues/3452
- [ ] https://github.com/rapidsai/cugraph/issues/3453
- [ ] https://github.com/rapidsai/cugraph/issues/3472
- [ ] https://github.com/rapidsai/cugraph/issues/3473
- [ ] https://github.com/rapidsai/cugraph/issues/3474
- [ ] https://github.com/rapidsai/cugraph/issues/3475
- [ ] https://github.com/rapidsai/cugraph/issues/3754
- [ ] https://github.com/rapidsai/cugraph/issues/3753
- [ ] https://github.com/rapidsai/cugraph/issues/3588
- [ ] https://github.com/rapidsai/cugraph/issues/4500
- [ ] https://github.com/rapidsai/cugraph/issues/4501
