### ISSUE TITLE
[FEA] OPG PageRank EPIC

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#26]
Start from [PRBench](https://github.com/NVIDIA/PRBench).

**Python**
 _(more details in the corresponding comment below)_ 
- [x] Define API
- [x] Create function that accepts DASK MPI call
- [x] makes call into CUDA MNMG routine (MPI-based) 
- [x] Validate that the data transit properly between the cuda device, the MPI rank and the dask worker

**CUDA**
- [x] API accepts cuDF columns
- [x] Refactor `main.cpp` as a set of library functions
- [x] Sort (pre-process with cuDF)
- [ ] Dedup
- [x] Create adjacency matrix
- [x] run PageRank
- [x] Validate / fix _(see details in the corresponding comment below)_ 
    - [x] Fix the size of the CSR matrix
    - [x] Check the impact of omitting dangling nodes
- [x] return answer _(vertex ID, pagerank)_
- [x] (optional) post-process to match NetworkX output

**Improvements**
- [x] C++11 support
- [ ] search for dead code
- [ ] Fix the path for int64_t indices 
- [ ] Replace macros by templates for the index type (to deploy 32bit and 64bit at the same time)
- [ ] Add namespace
- [x] Fix all warnings
- [ ] double check the custom memory pool (host)
- [ ] update MPI dependency in the conda env file to enable cuda-aware MPI once the package is available
- [ ] Modularize the code
- [ ] nvlink version
 
**Other**
- [x] cugraph integration  _(see details in the corresponding comment below)_ 
- [ ] Tests
   - [x] smoke test (single GPU) at C++  level
   - [x] multi-gpu test at C++ level
   - [x] Dask/MPI test (multiGPU)  at python level
- [ ] Documentation and sample

**Comment by afender** [comment]
### More information on Pagerank solver validation
We need to upgrade the code till we can validate the output against NetworkX solver. 

**Known issues**
- Currently, the feature that is supposed to load a real input instead of generating an artificial rmat one does not properly propagate the size of the graph. As a result, the rmat `scale` value is used and the last graph partition is always resized to the `scale` (scale 21 by default / ~ 2M vertices).

**Other smaller issues / things to check**
- The additional term for the dangling nodes in the iterative formulation has been omitted. We need to verify how much the result is impacted before releasing the code. 
- It is standard for Pagerank solvers to return a percentage (ie. that the Pagerank vector sums to 1.0).  It seems that PRBench computes the dominant eigenvector of the Google matrix.  We need to verify this. Assuming this understanding is correct, the following formula should allow to convert PRbench output to NetworkX output : `pr_res[i] = pr_res[i]/nrm1(pr_res)`. This can be seen as a post processing step using cuDF/Dask as `nrm1(pr_res)` is global operation on a gdf column.

**Comment by afender** [comment]
### More information on Python work
**Pre-processing** 
Input needs to be sorted by `source` using Dask/cuDF. 

**Wrapping input** 
Starting from dask/cuDF input, the python code should provide basic `gdf_columns` containing the local `source` and `destination` for each MPI rank at the C++ API level. 

**Warping output**
Each MPI rank will return the local Pagerank in a `gdf_columns` which should be properly warped at the python code level so that this output makes sense from Dask’s perspective.

**Post processing** 
See the last point of my previous comment

**Comment by afender** [comment]
### More information on cugraph integration
PRBench kernels need to be integrated in cugraph repo. The main dependencies that need to be taken care of are MPI and Dask. CuGraph build and tests system needs to be upgraded accordingly. These edits should be well encapsulated so that the MGMN code and dependencies can be enabled or disabled easily.

**Comment by afender** [comment]
### C++ API proposal 
`gdf_error gdf_multi_pagerank (const size_t global_v, const gdf_column *src_indices, const gdf_column *dest_indices, gdf_column *v_idx, gdf_column *pagerank, const float damping_factor = 0.85, const int max_iter = 20)`

A few notes:
- `global_v` is the total number of vertices of the graph.
- All `gdf_columns` contain data that is local to each node/GPU. Typicaly, each local size should be close to `num_global_edges/P`, where P is the number of process/GPUs. 
- `v_idx` is an output column that contains the vertex id corresponding to each pagerank element.
- `const float damping_factor = 0.85` and `const int max_iter = 20` are standard pagerank parameters

**Comment by afender** [comment]
On hold after talking to @BradReesWork.

Latest status:
We gathered all pieces under https://github.com/afender/cugraph/tree/multi_pagerank. This includes the benchmark notebook, dask-cudf in cugraph, MPI – cuda solver for PageRank and python bindings.
We implemented a basic pipeline that connects everything. At this point, we have successful runs on one GPU but multi GPU runs are still crashing.

**Comment by BradReesWork** [comment]
Closed.  Replaced by #485
