### ISSUE TITLE
MNMG Egonet

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cugraph#2916]
Update Egonet to support MNMG by using MNMG BFS and MNMG induced subgraph

Steps include:

- [x] Python implementation
- [x] Define PLC (pylibcugraph) API
- [x] Define C API
- [x] Define C++ API
- [x] Implement algorithm
- [x] Define C++ unit tests
- [x] Define C unit tests
- [x] Define Python unit tests
- [x] Delete legacy implementation

```[tasklist]
### Steps
- [ ] #2873
- [ ] #2906 
- [ ] #2907 
- [ ] #2908 
- [ ] #2909 
- [ ] #2910 
- [ ] #2911 
- [ ] #2912
```
