### ISSUE TITLE
[FEA] [EPIC] New C++ API 

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#307]
Cugraph should have a modern C++ API instead of a C API. 
 
- [x] Encapsulate the API in `namespace cugraph` (the backend needs to move to another namespace) #540 
- [x] get rid of `gdf_error` #498 
- [x] remove `gdf_` prefix
- [x] library handle (from RAFT) #523 
- [x] remove `gdf_column` #538
- [x] redo the graph object  
- [x] transition guide

**Comment by afender** [comment]
From Seungwha, about namespaces : 
If we're following cudf (https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/docs/TRANSITIONGUIDE.md),

We should use cugraph:: for public API, cugraph::detail:: for cugraph internal implementations, and anonymous namespace for implementations restricted to a single translation unit.

**Comment by afender** [comment]
From @BradReesWork, about cugraph handle :
get the device attributes and add a required statement on supported gpu types.

**Comment by afender** [comment]
#772 for the graph object

**Comment by afender** [comment]
Closing,  all of the linked pieces are done.
