### ISSUE TITLE
Update python Edge Betweenness Centrality to use C API

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cugraph#3147]
Enable edge betweenness centrality to follow the PLC path once a CAPI is available.

- [ ] Add Edge Betweenness Centrality to PLC
- [ ] Update PLC tests, docs, etc.
- [ ] Update cugraph to call Edge Betweenness Centrality in PLC
- [ ] Remove legacy Edge Betweenness Centrality in cugraph
```[tasklist]
### Tasks
- [ ] Look into NetworkX bug for BC
```
