### ISSUE TITLE
GNN Parking Lot

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3255]
```[tasklist]
- [ ] #2838 
- [ ] rapidsai/graph_dl#66
- [ ] rapidsai/graph_dl#94
- [ ] rapidsai/graph_dl#88
- [ ] rapidsai/graph_dl#59
- [ ] #3070
- [ ] #3072
- [ ] #3071 
- [ ] rapidsai/graph_dl#38
- [ ] #2982 
- [ ] #2984 
- [ ] rapidsai/graph_dl#64
- [ ] #2427 
- [ ] #3083 
- [ ] #3225
- [ ] https://github.com/rapidsai/cugraph/issues/3407
- [ ] https://github.com/rapidsai/cugraph/issues/3383
- [ ] https://github.com/rapidsai/cugraph/issues/3385
- [ ] https://github.com/rapidsai/cugraph/issues/2992
```
