### ISSUE TITLE
SG/SNMG/MNMG Automated Test System

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3262]
### Story statements:
* _"As a developer, I want to know if the tip of the current branch of cugraph is functionally correct and performing within runtime and memory expectations in SG, SNMG, and MNMG environments."_
* _"As a user, I would like to know the current performance metrics for the tip of the current branch and recent stable releases of cugraph and how it compares to other frameworks."_

### 23.04
* Update script to use nightly conda instead of from-source cugraph
  * Also incorporate GNN Docker image, which implies building nightly
* Update reporting to show individual pass/fail instead of only overall
* Update running script to allow for "run as much as you can" mode
* Add GNN E2E
  * Individual run for sampling
  * Individual run for training
* Create "weekly" mode
  * Subset of tests/benchmark for much larger scale - research what this will be
  * Push to same reporting channel
  * Get new S3 bucket from Ops (or research alternative for long-term history)

```[tasklist]
### 23.04 Tasks
- [ ] https://github.com/rapidsai/graph_dl/issues/134
- [ ] Update script to use nightly conda instead of from-source cugraph
- [ ] Update reporting to show individual pass/fail instead of only overall
- [ ] Update running script to allow for "run as much as you can" mode
- [ ] Add GNN E2E
- [ ] Create "weekly" mode
```

### 23.06
* Research alternative to ASV and implement

```[tasklist]
### 23.06 Tasks
- [ ] Research alternative to ASV and implement
```

**Comment by rlratzel** [comment]
Moved this Epic to an internal repo since it will not initially be available for use outside of Nvidia.
