### ISSUE TITLE
cugraph-service

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3335]
1. Plans
   a. The TigerGraph post will drive interest
2. Setup/configure tool or features
   a. Autosetup?
3. API
4. Performance
5. RPC framework
   a. gRPC vs Thrift
6. Exposed Algorithms
   a. Plan for when all cuGraph features will be exposed
7. Data processing
8. Marketing

<hr>

```[tasklist]
### User Stories - 24.02
- [ ] https://github.com/rapidsai/cugraph/issues/4050
```

```[tasklist]
### Stories to be scheduled
- [ ] #3112
- [ ] https://github.com/rapidsai/cugraph/issues/2655
- [ ] https://github.com/rapidsai/cugraph/issues/2677
- [ ] https://github.com/rapidsai/cugraph/issues/3118
- [ ] https://github.com/rapidsai/cugraph/issues/2876
- [ ] Figure out security
- [ ] Research BAM++
- [ ] BLOG on cugraph-service
```

**Comment by BradReesWork** [comment]
Marking as closed since cugraph service has been dropped
