### ISSUE TITLE
[Epic] Notebooks Cleanup

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3368]
Clean-up and/or create notebooks

```[tasklist]
### Notebook fixes
- [ ] https://github.com/rapidsai/cugraph/issues/2198
```

```[tasklist]
### Ensure Notebooks work in CI - benchmarks can be skipped
- [ ] Algorithms
- [ ] Applications
- [ ] Demos
- [ ] GNN
- [ ] Modules
```

```[tasklist]
### New Notebooks
- [ ] https://github.com/rapidsai/cugraph/issues/2669
```

```[tasklist]
### GNN Notebooks
- [ ] https://github.com/rapidsai/cugraph/issues/3072
```

-----
**Improve usability of community cugraph notebooks**
This work was requested by Taurean Dyer. Including the tasks as discussed.

- tracker that maps notebooks to the containers they run in
- keep all notebooks that only run in rapids in rapids depot
- group notebooks by the containers ( out of rapids depot ) find a new home
- update the readme's to reflect the necessary container for notebooks
- link from cugraph readme to the notebook areas that require custom containers.
- make sure brad is on board with this.
- give you the docker run commands to run the notebook

Done criteria, the notebooks below
https://github.com/rapidsai/cugraph/tree/main/notebooks/demo
https://github.com/rapidsai/cugraph/tree/main/notebooks/applications
https://github.com/rapidsai-community/notebooks-contrib/tree/main/community_tutorials_and_guides/cugraph

All contain instructions to run them if anything beyond the default cuGraph conda environment is needed. This includes dependencies and docker commands if necessary

```[tasklist]
### Improve usability of community cugraph notebooks
- [ ] #192
- [ ] #193
- [ ] #195
- [ ] rapidsai/cugraph#3593
```

**Comment by BradReesWork** [comment]
closing
