### ISSUE TITLE
Decouple PropertyGraph from cugraph

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3457]
Who: end users, cugraph developers
What: move PropertyGraph to a separate package
Why: This allows PropertyGraph to add dependencies specific to PG use cases without impacting cugraph users. This also allows for PG use cases to be supported without installing cugraph and its dependencies (eg. a workflow calling PG and PLC)

* New conda and PIP package
* `property-graph` subdir under `cugraph/python` (PG code stays in cugraph monorepo) - or do we want a different name?
* Should not depend on cugraph (but can depend on PLC or other lower-level libs if necessary?).

Questions: 
* should cugraph depend on PG, perhaps if we want `cugraph.Graph` to have support for properties like NetworkX Graph?  Note: this could change a few statements above (eg. PG adds deps that don't impact cugraph users).

```[tasklist]
### Tasks
- [ ] Move experimental PG code to new subdir in source tree, peer to cugraph, cugraph-service, cugraph-dgl, etc.
- [ ] Move PG tests to test location specific to new PG subdir in source tree
- [ ] Update CI scripts to build new PG package and run newly-located tests
- [ ] Add conda recipe, setup.py, etc. for new PG packages
- [ ] Add/update docs for new PG package
- [ ] Add/update notebook(s) for new PG package
```

**Comment by rlratzel** [comment]
* we'll be creating a completely new implementation with no guarantees of backwards-compatibility with `cugraph.experimental.property_graph`
  * we'll deprecate experimental PG starting in 23.08
  * cugraph-pg will provide a "comparable" feature set to experimental
    * add heterogeneous data, query, extract subgraph

**Comment by rlratzel** [comment]
https://github.com/rapidsai/cugraph/pull/3618
