### ISSUE TITLE
Planning Epic

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3479]
# Long-term planning

## Broad form benchmarking

Need to track and measure against industry benchmarks - this facilitates marketing activities as well as showing that we can perform at a level better than the open source offerings.

While those benchmarks are important, our customers are most concerned with finding solutions to problems. Because of this we also need to focus on end-to-end benchmarking.

```[tasklist]
### Benchmarking
- [ ] Multi-node multi-gpu
- [ ] End-to-end workflows
- [ ] performance comparison across product layers
```

## Dynamic Graph - Live In-memory

Research approach @ChuckHastings and @seunghwak 

```[tasklist]
### Dynamic Graph
- [ ] Discovery Discussion
- [ ] Document Requirements
- [ ] Layout out phases and expectations
- [ ] Share plans w/ and gather customer requirements
- [ ] Defined and attribute user stories
```

## All Paths w/ Constraints Algorithm

Research approach @ChuckHastings and @seunghwak 

```[tasklist]
### All Paths w/ Constraints
- [ ] Discovery Discussion
- [ ] Document Requirements
- [ ] Layout out phases and expectations
- [ ] Share plans w/ and gather customer requirements
- [ ] Defined and attribute user stories
- [ ] #2918 
```

## Data Masking

Research approach @ChuckHastings and @seunghwak 

```[tasklist]
### Data Masking
- [ ] Discovery Discussion
- [ ] Document Requirements
- [ ] Layout out phases and expectations
- [ ] Share plans w/ and gather customer requirements
- [ ] Defined and attribute user stories
```

**Comment by kingmesal** [comment]
place holder is complete. closing.
