### ISSUE TITLE
Make Customer-facing notebooks more user-friendly

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#3534]
```[tasklist]
### Tasks
- [ ]  #3394
- [ ]  #3395
- [ ] #3396
- [ ] #3398
- [ ] Tracker to map environments to notebooks
- [ ] Reorganize notebooks based on environment
- [ ] Update docs to explain running notebooks
- [ ] Write docker instructions for additional dependencies needed
```

This covers notebooks in 
https://github.com/rapidsai/cugraph/tree/main/notebooks/demo
https://github.com/rapidsai/cugraph/tree/main/notebooks/applications
https://github.com/rapidsai-community/notebooks-contrib/tree/main/community_tutorials_and_guides/cugraph

This is work requested by Taurean Dyer
