### ISSUE TITLE
Improve performance/efficiency in cugraph python

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3587]
_This needs a more concise title and done criteria_

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/cugraph/issues/2719
- [ ] https://github.com/rapidsai/cugraph/issues/2711
- [ ] https://github.com/rapidsai/cugraph/issues/2011
- [ ] https://github.com/rapidsai/cugraph/issues/2746
- [ ] https://github.com/rapidsai/cugraph/issues/2768
- [ ] ensure benchmarks are in place to track perf gains
```

**Comment by rlratzel** [comment]
* We need to verify there is/isn't algos that don't use PLC graphs
*

**Comment by rlratzel** [comment]
This did not get completed in 23.10 but will be addressed in a future release. Since the individual tasks are already captured in #3304, new stories will be created in future releases that are better defined, so this is being closed.
