### ISSUE TITLE
MNMG K-Truss for cugraph python

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3588]
```[tasklist]
### Tasks
- [ ] add python MG implementation 
- [ ] MG unit tests
- [ ] docstring w/ example (also runs in doctest)
```

**Comment by rlratzel** [comment]
20240103 - on track for 24.02 release.  Draft PR is up, but only for C++ code.  Python updates should be up mid January.

**Comment by rlratzel** [comment]
Moving this to 24.06 since 24.04 will only have SG support for the new primitive-based implementation.

**Comment by ChuckHastings** [comment]
Believe this was closed by https://github.com/rapidsai/cugraph/pull/4438
