### ISSUE TITLE
MNMG BC Edge for cugraph python

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#3589]
```[tasklist]
### Tasks
- [ ] docstring w/ example (also runs in doctest)
- [ ] SG unit tests
- [ ] MG unit tests
- [ ] implementation (SG & MG)
- [ ] PLC
```

**Comment by rlratzel** [comment]
duplicate of https://github.com/rapidsai/cugraph/issues/3147
