### ISSUE TITLE
Improve cuGraph-PyG MFG Creation Time

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3644]
Currently, we have a bottleneck in the MFG creation step in training GNNs with cuGraph-PyG.  Resolving this involves creating a new C++ function to handle MFG creation, and hopefully also expose additional parallelism.

This story will be updated with additional details soon.

```[tasklist]
### Tasks
- [x] Get current performance benchmark numbers and add them to this story
- [x] Add code describing the expected behavior of the C++ function to this story
- [x] Create the C++ function (this may be delegated to another team)
- [x] Integrate the C++ function into cuGraph-PyG
```

```
------------------------------------------------------------- benchmark: 3 tests ------------------------------------------------------------
Name (time in ms, mem in bytes)        Mean               GPU mem            GPU Leaked mem            Rounds            GPU Rounds          
---------------------------------------------------------------------------------------------------------------------------------------------
test_feature_fetch[10]               3.8067 (1.0)               0 (1.0)                   0 (1.0)           1           1
test_feature_fetch[100]             29.5605 (7.77)              0 (1.0)                   0 (1.0)           1           1
test_mfg_creation                   36.2376 (9.52)     56,369,352 (inf)           9,053,936 (inf)           1           1
---------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```
