### ISSUE TITLE
[FEA]: Create a multi column dataset and add to the base test for every algorithm

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#3900]
Every algorithm should be testing that it can handle processing a Multi-Column dataset - this is really a test of the underlying renumbering service.

```[tasklist]
### Tasks
- [ ] Create a multi-column dataset
- [ ] Add the dataset of Datasets (data in S3 and metadate file create)
- [ ] Add the dataset to the standard dataset array
```

**Comment by BradReesWork** [comment]
seems like a duplicate of #1575
