### ISSUE TITLE
Update nx-cugraph README/docs for 24.02

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#4079]
The README.md file indicating the state of nx-cugraph support for NetworkX needs to be updated to reflect
* new algos added for 24.02
* planned algos for future releases

It should also be improved to show NetworkX APIs, and put less of an emphasis (perhaps just remove altogether) the PLC APIs.

PR rapidsai/cugraph#4069 will help here.
```[tasklist]
### Tasks
- [x] merge rapidsai/cugraph#4069
- [ ] update README with output from scripts in rapidsai/cugraph#4069
- [ ] Discuss and add updates for 24.04+ to README (to serve as a crude roadmap for users)
```

**Comment by rlratzel** [comment]
closed too early due to a linked PR for 1 task being closed
