### ISSUE TITLE
[BUG] Update dependencies versions

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#440]
- [ ] [**dev starts**] Update ci (`build.sh`) and conda folders (`recipe` and `env`) to use nightly RAPIDS packages of the version we are working on. This should be done first when we start working on a new release cycle. This involves upgrading:
   - cudf 
   - rmm 
   - dask-cuda  
   - dask-cudf 

- [ ] [**dev ends**] Check that third-party versions are in sync with cudf dev env. This involves checking (non-exhaustive and subject to change):
   - pandas 
   - pyarrow 
   - distributed
   - dask 
  
- [ ] [**code Freeze**] verify third-party versions again

**Comment by afender** [comment]
- Done for 0.10
- Reseting for 0.11

**Comment by afender** [comment]
Done for 0.11
Reseting for 0.12

**Comment by afender** [comment]
Verified today for 0.12

**Comment by afender** [comment]
Verified today for 0.13
Resetting for 0.14

**Comment by afender** [comment]
#911 for 0.14.

**Comment by afender** [comment]
Verified today for 0.16, conda env updated last week for nccl and explicit libcudf/librmm 
Resetting for 0.17
