### ISSUE TITLE
[FEA] Get rid of gdf_column

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#538]
cuGraph uses `gdf_column` as a device array container in the C++ API. As CuDF is depreciating `gdf_column`, we need a new device array container. There are hundreds of occurrences in cuGraph.

- Replace `gdf_column` in the API
- Update all tests
- Update bindings
- Update doc

- [ ] katz_centrality.cu
- [ ] nvgraph.gdf.cu
- [ ] ECG.cu
- [ ] connectivity.cu
- [ ] core_number.cu
- [ ] db_object.cu
- [ ] jaccard.cu
- [ ] overlap.cu
- [ ] two_hop_neighbors.cu
